CREATE TABLE item (
	product_id INTEGER REFERENCES product(id),
	SIZE INTEGER NOT NULL,
	color VARCHAR(30) NOT NULL,
	picture VARCHAR(256) NOT NULL,
	price NUMERIC(6, 2) NOT NULL,
	id SERIAL PRIMARY KEY
);